from typing import Optional, Protocol
from uuid import UUID

from src.domain.models import Product, SharedList

class ProductsPort(Protocol):
    def get_all_products(self) -> list[Product]: ...
    def get_product(self, product_id: UUID) -> Optional[Product]: ...
    def get_products_by_list(self, list_id: UUID) -> list[Product]: ...
    def create_product(self, product: Product) -> Product: ...
    def update_product(self, product_id: UUID, product: Product) -> Product: ...
    def update_product_status(self, product_id: UUID, status: str) -> Product: ...
    def delete_product(self, product_id: UUID) -> bool: ...

class SharedListsPort(Protocol):
    def get_all_shared_lists(self) -> list[SharedList]: ...
    def get_shared_list(self, list_id: UUID) -> Optional[SharedList]: ...
    def create_shared_list(self, shared_list: SharedList) -> SharedList: ...
    def update_shared_list(self, list_id: UUID, shared_list: SharedList) -> SharedList: ...
    def delete_shared_list(self, list_id: UUID) -> bool: ...